Fiap.Leilao.Web/Controllers/ComprarController.cs
using Fiap.Leilao.Dominio.Models;
using Fiap.Leilao.Persistencia.UnitsOfWork;
using Fiap.Leilao.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap.Leilao.Web.Controllers
{
    [Authorize]
    public class ComprarController : Controller
    {
        private UnitOfWork _unit = new UnitOfWork();
        #region GET
        [HttpGet]
        public ActionResult Dashboard()
        {

            CompraViewModel compras = PopulaLista();
            return View(compras);
        }
        [HttpGet]
        public ActionResult Buscar(string nomeBusca)
        {
            var usuario = _unit.UsuarioRepository.BuscarPor(a => a.Email == User.Identity.Name);
            var id = usuario.First().Id;
            var lista = _unit.ProdutoRepository.BuscarPor(a => a.Nome.Contains(nomeBusca) && a.Status_Produto == "Vendendo" && a.Id_Vendedor != id);
            var viewModel = new CompraViewModel()
            {
                Produtos = lista
            };
            return PartialView("_tabela", viewModel);

        }
        [AllowAnonymous]
        [HttpGet]
        public ActionResult BuscarHome(string nomeBusca)
        {

            var lista = _unit.ProdutoRepository.BuscarPor(a => a.Nome.Contains(nomeBusca) && a.Status_Produto == "Vendendo");
            var viewModel = new CompraViewModel()
            {
                Produtos = lista
            };
            return PartialView("_tabela", viewModel);

        }
        [AllowAnonymous]
        [HttpGet]
        public ActionResult Home()
        {

            CompraViewModel compras = new CompraViewModel
            {
                Produtos = _unit.ProdutoRepository.BuscarPor(p => p.Status_Produto == "Vendendo")
            };
            return View(compras);
        }
        #endregion
        #region POST
        [HttpPost]
        public ActionResult Dashboard(CompraViewModel compraViewModel)
        {
            var usuario = _unit.UsuarioRepository.BuscarPor(a => a.Email == User.Identity.Name);
            var id = usuario.First().Id;
            var negociacao = new Negociacao
            {
                Id_Produto = compraViewModel.Id_Produto,
                Valor_Produto = compraViewModel.Valor_Produto,
                Id_Comprador = id, // alterar na autenticacao
                Status = "Aguardando Resposta"
            };
            var produto = _unit.ProdutoRepository.BuscarPorId((int)compraViewModel.Id_Produto);
            produto.Status_Produto = "Em negociação";
            _unit.ProdutoRepository.Alterar(produto);
            _unit.NegociacaoRepository.Cadastrar(negociacao);
            _unit.Salvar();
            CompraViewModel compras = PopulaLista();
            return RedirectToAction("Dashboard", "Usuario");

        }
        #endregion
        #region Private
        private CompraViewModel PopulaLista()
        {
            var usuario = _unit.UsuarioRepository.BuscarPor(a => a.Email == User.Identity.Name);
            var id = usuario.First().Id;
            return new CompraViewModel()
            {

                Produtos = _unit.ProdutoRepository.BuscarPor(p => p.Status_Produto == "Vendendo" && p.Id_Vendedor != id)

            };
        }
        #endregion


        
       
    }
}

Fiap.Leilao.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Leilon - Trazendo Eficácia para sua compras Online</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/estilos.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <nav class="nav">
        <div class="container">
            <a href='@Url.Action("Home", "Comprar")'>
                <img src="~/Content/imagens/leilon.png" />
            </a>
            <ul>@if (User.Identity.IsAuthenticated)
            {
                <li>@Html.ActionLink("Painel", "Dashboard", "Usuario", new { area = "" }, new { @class = "navbar-brand" })</li>
                <li>@Html.ActionLink("Comprar", "Dashboard", "Comprar", new { area = "" }, new { @class = "navbar-brand" })</li>
                <li>@Html.ActionLink("Vender", "Dashboard", "Vender", new { area = "" }, new { @class = "navbar-brand" })</li>
                <li class="logado">Olá! @User.Identity.Name</li>
                <li>@Html.ActionLink("Sair", "LogOut", "User", new { area = "" }, new { @class = "navbar-brand" })</li>
            }
            else
            {
                <li>@Html.ActionLink("Home", "Home", "Comprar", new { area = "" }, new { @class = "navbar-brand" })</li>
                <li> @Html.ActionLink("Login", "LogIn", "User", new { area = "" }, new { @class = "navbar-brand" })</li>
                 <li>@Html.ActionLink("Registrar-se", "Register", "User", new { area = "" }, new { @class = "navbar-brand" })</li>
            }
            </ul>
        </div>
    </nav>
    <div class="cadastrotopo">@RenderSection("cadastrotopo", false)</div>
    <div class="login-layout">@RenderSection("login", false)</div>
    <div class="header-layout">@RenderSection("topo", false)</div>
    <div class="busca-layout">@RenderSection("busca", false)</div>


    <div class="container body-content">
        @RenderBody()
        <hr />

    </div>
    <div class="vantagens-layout">@RenderSection("vantagens", false)</div>
    <footer class="container">
        <p>&copy; @DateTime.Now.Year - Grupo do Fábrica de Desenvolvedores</p>
    </footer>
    <script src="~/scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/scripts/jquery-ui-1.12.1.min.js"></script>
    <script src="~/scripts/jquery.unobtrusive-ajax.min.js"></script>
    @RenderSection("scripts", false)
</body>
</html>