Fiap.Leilao.Web/Controllers/VenderController.cs
using Fiap.Leilao.Dominio.Models;
using Fiap.Leilao.Persistencia.UnitsOfWork;
using Fiap.Leilao.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap.Leilao.Web.Controllers
{
    [Authorize]
    public class VenderController : Controller
    {
        private UnitOfWork _unit = new UnitOfWork();
        #region GET
        [HttpGet]
        public ActionResult DashBoard(string msg)
        {
            var usuario = _unit.UsuarioRepository.BuscarPor(a => a.Email == User.Identity.Name);
            var id = usuario.First().Id;
            var viewModel = new ProdutoViewModel()
            {
                Mensagem = msg,
                Produtos = _unit.ProdutoRepository.BuscarPor(a => a.Id_Vendedor == id)
            };
            return View(viewModel);
        }
        [HttpGet]
        public ActionResult Buscar(string nomeBusca)
        {
            var usuario = _unit.UsuarioRepository.BuscarPor(a => a.Email == User.Identity.Name);
            var id = usuario.First().Id;
            var lista = _unit.ProdutoRepository.BuscarPor(a => a.Nome.Contains(nomeBusca) && a.Id_Vendedor == id);
            var viewModel = new ProdutoViewModel()
            {
                Produtos = lista
            };
            return PartialView("_tabela", viewModel);

        }
        #endregion
        #region POST
        [HttpPost]
        public ActionResult Cadastrar(ProdutoViewModel viewModel)
        {
            var usuario = _unit.UsuarioRepository.BuscarPor(a => a.Email == User.Identity.Name);
            Produto produto = new Produto()
            {
                Id = viewModel.Id,
                Nome = viewModel.Nome,
                Descricao = viewModel.Descricao,
                Imagem = viewModel.Imagem,
                Id_Vendedor = usuario.First().Id,
                Valor_Vendedor = viewModel.Valor_Vendedor,
                Status_Produto = "Vendendo"
            };
            _unit.ProdutoRepository.Cadastrar(produto);
            _unit.Salvar();
            return RedirectToAction("DashBoard");
        }
        [HttpPost]
        public ActionResult Excluir(int produtoId)
        {
            var negociacoes = _unit.NegociacaoRepository.BuscarPor(a => a.Id_Produto == produtoId);
            foreach (var item in negociacoes)
            {
                _unit.NegociacaoRepository.Remover(item.Id);
            }

            _unit.ProdutoRepository.Remover(produtoId);
            _unit.Salvar();
            return RedirectToAction("DashBoard", new { msg = "Produto Deletado com sucesso!" });
        }
        [HttpPost]
        public ActionResult Editar(ProdutoViewModel viewModel)
        {
            Produto Produto = new Produto()
            {
                Id = viewModel.Id,
                Nome = viewModel.Nome2,
                Descricao = viewModel.Descricao2,
                Imagem = viewModel.Imagem2,
                Valor_Vendedor = viewModel.Valor_Vendedor2,
                Id_Vendedor = viewModel.Id_Vendedor2,
                Status_Produto = viewModel.Status_Produto
            };
            _unit.ProdutoRepository.Alterar(Produto);
            _unit.Salvar();
            return RedirectToAction("DashBoard", new { msg = "Produto Alterado com sucesso!" });
        }
        #endregion
    }
}

Fiap.Leilao.Web/Views/Vender/Dashboard.cshtml
@model Fiap.Leilao.Web.ViewModels.ProdutoViewModel
@{
    ViewBag.Title = "Produtos";
}
<div class="espaco" /> </div>
@MeuHelper.Titulo("Vender Produtos")


<button type="button" class="botaolaranja" data-toggle="modal" data-target="#myModalCadastrar">
    Cadastrar Produtos
</button>


<!--listar-->
<hr />
@using (Ajax.BeginForm("Buscar", null, new AjaxOptions { HttpMethod = "get", UpdateTargetId = "tabela", InsertionMode = InsertionMode.Replace }, new { @class = "form-inline", id = "formularioBusca" }))
{

    <div class="form-group">
        @Html.TextBox("nomeBusca", "", new { @class = "form-control", placeholder = "Filtrar pelo nome" })
    </div>
}
<table class="table table-striped">
    <thead>
        <tr>
            <td>Id</td>
            <td>Imagem</td>
            <td>Nome</td>
            <td>Descrição</td>
            <td>Preço</td>
            <td>Status</td>
        </tr>
    </thead>
    <tbody id="tabela">
        @Html.Partial("_tabela", Model)

    </tbody>
</table>





<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Confirmação</h4>
            </div>
            <div class="modal-body">
                Realmente dezeja apagar o Produto?
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("Excluir", "Vender"))
                {
                    <input type="hidden" id="produtoId" name="produtoId" />
                    <button type="submit" class="btn btn-primary">Sim</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Não</button>
                }

            </div>
        </div>
    </div>
</div>





<div class="modal fade" id="myModalEditar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Editar Produto</h4>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Editar", "Vender", FormMethod.Post, new { @class = "form-horizontal" }))
                {
                    <p class="nome-modal">Dê um novo nome...</p>
                    <div class="form-group">
                        @Html.TextBoxFor(p => p.Nome2, new { @class = "inputs-modal", placeholder = "Nome" })
                    </div>
                    <p class="nome-modal">O que deseja alterar na descrição do produto...</p>
                    <div class="form-group">
                        @Html.TextAreaFor(p => p.Descricao2, new { @class = "inputs-modal textareaformatacao", placeholder = "Descricao" })
                    </div>
                    <p class="nome-modal">Insira uma imagem com o endereço URL...</p>
                    <div class="form-group">
                        @Html.TextBoxFor(p => p.Imagem2, new { @class = "inputs-modal", placeholder = "Imagem" })
                    </div>
                    <p class="nome-modal">Novo valor do produto...</p>
                    <div class="form-group">
                        @Html.TextBoxFor(p => p.Valor_Vendedor2, new { @class = "inputs-modal", placeholder = "Valor" })
                    </div>
                    @Html.HiddenFor(p => p.Id)
                    @Html.HiddenFor(p => p.Id_Vendedor2)
                    @Html.HiddenFor(p => p.Status_Produto)
                    <div class="botoes">
                        @MeuHelper.Submit("Salvar Alteração", "btn-oferta")

                        <button type="button" class="btn-cancelar" data-dismiss="modal">Cancelar</button>
                    </div>  }
            </div>
        </div>
    </div>
</div>



<div class="modal fade" id="myModalCadastrar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Cadastrar Produto</h4>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Cadastrar", "Vender", FormMethod.Post, new { @class = "form-horizontal" }))
                {
                    <p class="nome-modal">Dê um nome...</p>
                    <div class="form-group">
                        @Html.TextBoxFor(p => p.Nome, new { @class = "inputs-modal", placeholder = "Nome" })
                    </div>
                    <p class="nome-modal">Dê uma descrição...</p>
                    <div class="form-group">
                        @Html.TextAreaFor(p => p.Descricao, new { @class = "inputs-modal textareaformatacao", placeholder = "Descriçao"})
                    </div>
                    <p class="nome-modal">Insira uma imagem com o endereço URL...</p>
                    <div class="form-group">
                        @Html.TextBoxFor(p => p.Imagem, new { @class = "inputs-modal", placeholder = "Imagem" })
                    </div>
                    <p class="nome-modal">Qual o valor do produto?</p>
                            <div class="form-group">
                                @Html.TextBoxFor(p => p.Valor_Vendedor, new { @class = "inputs-modal", placeholder = "Valor" })
                            </div>
                            <div class="botoes">
                                @Html.HiddenFor(p => p.Id_Vendedor)
                                @MeuHelper.Submit("Cadastrar", "btn-oferta")

                                <button type="button" class="btn-cancelar" data-dismiss="modal">Cancelar</button>

                            </div>
                }
            </div>
        </div>
    </div>
</div>


@section scripts{
    <script>
        function someBotao() {
            $("td > button , td > a").css("visibility", "hidden");

            $("tr").hover(function () {
                $(this).find("button,a").css("visibility", "visible");
            }, function () {
                $(this).find("button,a").css("visibility", "hidden");
            });

        }
        $().ready(function () {
            someBotao();
            $("#nomeBusca").change(function () {
                $("#formularioBusca").submit();
            });
        });
    </script>
}

Fiap.Leilao.Web/Views/Vender/_tabela.cshtml
@model Fiap.Leilao.Web.ViewModels.ProdutoViewModel
@foreach (var item in Model.Produtos)
{
    <tr>
        <td>@item.Id</td>
        <td>
            <img src=@item.Imagem class="img-thumbnail" alt=@item.Imagem width="100" height="50">
        </td>
        <td>@item.Nome</td>
        <td>@item.Descricao</td>
        <td>@item.Valor_Vendedor</td>
        <td>@item.Status_Produto</td>
        <td>
            <button onclick="Nome2.value = '@item.Nome',Descricao2.value = '@item.Descricao',Imagem2.value = '@item.Imagem', Id.value = '@item.Id',Valor_Vendedor2.value='@item.Valor_Vendedor',Id_Vendedor2.value='@item.Id_Vendedor',Status_Produto.value='@item.Status_Produto'" type="button" class="botaolaranja" data-toggle="modal" data-target="#myModalEditar">
                Editar
            </button>

            <button onclick="produtoId.value = @item.Id" type="button" class="btn-cancelar" data-toggle="modal" data-target="#myModal">
                Excluir
            </button>
        </td>
    </tr>
}
@if (Request.IsAjaxRequest())
{
    <script>
        someBotao();

    </script>
}